# Generated by Django 6.0.4 on 2026-04-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0002_ad_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="is_top",
            field=models.BooleanField(
                default=False,
                help_text="Выделяется в поиске и получает приоритет",
                verbose_name="Топ объявление",
            ),
        ),
    ]
