# Generated by Django 6.0.4 on 2026-04-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0004_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ad",
            name="create_at",
        ),
    ]
