# Generated by Django 6.0.4 on 2026-04-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0006_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
