# Generated by Django 6.0.4 on 2026-04-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0007_delete_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
